Repository GetStream/stream-feeds-android, pull requests merged in 2025-09, with the labels that each got.

#59 Add missing KDoc on public FeedsClient properties.
  stream-feeds-android-client/src/main/kotlin/io/getstream/feeds/android/client/api/FeedsClient.kt
Labels: pr:documentation

#57 Read product and productVersion from BuildConfig.
  stream-feeds-android-client/src/main/kotlin/io/getstream/feeds/android/client/internal/client/Create.kt
Labels: pr:bug

#58 Remove dependency on `stream-log`.
  gradle/libs.versions.toml
  stream-feeds-android-client/build.gradle.kts
  stream-feeds-android-client/src/main/kotlin/io/getstream/feeds/android/client/internal/client/Create.kt
  stream-feeds-android-client/src/main/kotlin/io/getstream/feeds/android/client/internal/client/FeedsClientImpl.kt
  stream-feeds-android-client/src/main/kotlin/io/getstream/feeds/android/client/internal/client/reconnect/ConnectionRecoveryHandler.kt
  stream-feeds-android-client/src/main/kotlin/io/getstream/feeds/android/client/internal/log/Logging.kt
  stream-feeds-android-client/src/test/kotlin/io/getstream/feeds/android/client/internal/client/FeedsClientImplTest.kt
  stream-feeds-android-sample/build.gradle.kts
  stream-feeds-android-sample/src/main/java/io/getstream/feeds/android/sample/log/InMemoryLogger.kt
  stream-feeds-android-sample/src/main/java/io/getstream/feeds/android/sample/ui/LogsScreen.kt
Labels: pr:internal

#60 Add missing tests to ActivityCommentListStateImpl
  metrics/stream-feeds-android-metrics/.gitignore
  stream-feeds-android-client/src/main/kotlin/io/getstream/feeds/android/client/internal/repository/DevicesRepositoryImpl.kt
  stream-feeds-android-client/src/main/kotlin/io/getstream/feeds/android/client/internal/state/ActivityCommentListStateImpl.kt
  stream-feeds-android-client/src/test/kotlin/io/getstream/feeds/android/client/internal/repository/BookmarksRepositoryImplTest.kt
  stream-feeds-android-client/src/test/kotlin/io/getstream/feeds/android/client/internal/repository/RepositoryTestUtils.kt
  stream-feeds-android-client/src/test/kotlin/io/getstream/feeds/android/client/internal/state/ActivityCommentListStateImplTest.kt
  stream-feeds-android-client/src/test/kotlin/io/getstream/feeds/android/client/internal/test/TestData.kt
  stream-feeds-android-sample/src/main/res/xml/data_extraction_rules.xml
Labels: pr:test

#63 Enable sonar analysis for the Feeds project
  .github/workflows/android.yml
Labels: pr:ci

#65 Display image attachments in comments
  stream-feeds-android-sample/src/main/java/io/getstream/feeds/android/sample/feed/CommentsBottomSheet.kt
  stream-feeds-android-sample/src/main/java/io/getstream/feeds/android/sample/feed/CommentsSheetViewModel.kt
  stream-feeds-android-sample/src/main/java/io/getstream/feeds/android/sample/feed/CreateContentBottomSheet.kt
  stream-feeds-android-sample/src/main/java/io/getstream/feeds/android/sample/feed/FeedsScreen.kt
  stream-feeds-android-sample/src/main/java/io/getstream/feeds/android/sample/feed/ImageAttachmentsSection.kt
Labels: pr:demo-app

#66 Allow editing and deleting comments
  stream-feeds-android-sample/src/main/java/io/getstream/feeds/android/sample/feed/CommentsBottomSheet.kt
  stream-feeds-android-sample/src/main/java/io/getstream/feeds/android/sample/feed/CommentsSheetViewModel.kt
  stream-feeds-android-sample/src/main/java/io/getstream/feeds/android/sample/feed/ContentContextMenuDialog.kt
  stream-feeds-android-sample/src/main/java/io/getstream/feeds/android/sample/feed/EditContentDialog.kt
  stream-feeds-android-sample/src/main/java/io/getstream/feeds/android/sample/feed/FeedsScreen.kt
  stream-feeds-android-sample/src/main/java/io/getstream/feeds/android/sample/ui/util/ComposeExtensions.kt
Labels: pr:demo-app

#67 Add workflow to clean stale PRs
  .github/workflows/pr-clean-stale.yaml
Labels: pr:ci

#70 Show progress indicator while posting content
  stream-feeds-android-sample/src/main/java/io/getstream/feeds/android/sample/feed/CommentsBottomSheet.kt
  stream-feeds-android-sample/src/main/java/io/getstream/feeds/android/sample/feed/CommentsSheetViewModel.kt
  stream-feeds-android-sample/src/main/java/io/getstream/feeds/android/sample/feed/CreateContentBottomSheet.kt
  stream-feeds-android-sample/src/main/java/io/getstream/feeds/android/sample/feed/CreatePollButton.kt
  stream-feeds-android-sample/src/main/java/io/getstream/feeds/android/sample/feed/FeedViewModel.kt
  stream-feeds-android-sample/src/main/java/io/getstream/feeds/android/sample/feed/FeedsScreen.kt
Labels: pr:demo-app

#61 Rewatch feeds on socket reconnection
  stream-feeds-android-client/src/main/kotlin/io/getstream/feeds/android/client/internal/client/Create.kt
  stream-feeds-android-client/src/main/kotlin/io/getstream/feeds/android/client/internal/client/FeedsClientImpl.kt
  stream-feeds-android-client/src/main/kotlin/io/getstream/feeds/android/client/internal/client/reconnect/FeedWatchHandler.kt
  stream-feeds-android-client/src/main/kotlin/io/getstream/feeds/android/client/internal/state/FeedImpl.kt
  stream-feeds-android-client/src/test/kotlin/io/getstream/feeds/android/client/internal/client/FeedsClientImplTest.kt
  stream-feeds-android-client/src/test/kotlin/io/getstream/feeds/android/client/internal/client/reconnect/FeedWatchHandlerTest.kt
  stream-feeds-android-client/src/test/kotlin/io/getstream/feeds/android/client/internal/state/FeedImplTest.kt
Labels: pr:new-feature

#69 Allow clients to configure logging
  stream-feeds-android-client/src/main/kotlin/io/getstream/feeds/android/client/api/logging/HttpLoggingLevel.kt
  stream-feeds-android-client/src/main/kotlin/io/getstream/feeds/android/client/api/logging/Logger.kt
  stream-feeds-android-client/src/main/kotlin/io/getstream/feeds/android/client/api/logging/LoggingConfig.kt
  stream-feeds-android-client/src/main/kotlin/io/getstream/feeds/android/client/api/model/FeedsConfig.kt
  stream-feeds-android-client/src/main/kotlin/io/getstream/feeds/android/client/internal/client/Create.kt
  stream-feeds-android-client/src/main/kotlin/io/getstream/feeds/android/client/internal/logging/FeedsLoggerProvider.kt
  stream-feeds-android-client/src/main/kotlin/io/getstream/feeds/android/client/internal/logging/LoggingFactory.kt
  stream-feeds-android-client/src/test/kotlin/io/getstream/feeds/android/client/internal/logging/CustomLoggerProviderTest.kt
  stream-feeds-android-sample/src/main/java/io/getstream/feeds/android/sample/login/LoginManager.kt
Labels: pr:new-feature

#75 Extend unit tests to uncovered code
  metrics/.gitignore
  stream-feeds-android-client/src/main/kotlin/io/getstream/feeds/android/client/internal/http/FeedsSingleFlightApi.kt
  stream-feeds-android-client/src/test/kotlin/io/getstream/feeds/android/client/internal/client/FeedsClientImplTest.kt
  stream-feeds-android-client/src/test/kotlin/io/getstream/feeds/android/client/internal/client/reconnect/lifecycle/StreamLifecycleObserverTest.kt
  stream-feeds-android-client/src/test/kotlin/io/getstream/feeds/android/client/internal/http/FeedsSingleFlightApiTest.kt
  stream-feeds-android-client/src/test/kotlin/io/getstream/feeds/android/client/internal/repository/ActivitiesRepositoryImplTest.kt
  stream-feeds-android-client/src/test/kotlin/io/getstream/feeds/android/client/internal/repository/CommentsRepositoryImplTest.kt
  stream-feeds-android-client/src/test/kotlin/io/getstream/feeds/android/client/internal/repository/PollsRepositoryImplTest.kt
  stream-feeds-android-client/src/test/kotlin/io/getstream/feeds/android/client/internal/serialization/FeedsEventParserTest.kt
  stream-feeds-android-client/src/test/kotlin/io/getstream/feeds/android/client/internal/serialization/FeedsMoshiJsonParserTest.kt
  stream-feeds-android-client/src/test/kotlin/io/getstream/feeds/android/client/internal/state/ActivityImplTest.kt
  stream-feeds-android-client/src/test/kotlin/io/getstream/feeds/android/client/internal/state/CommentReplyListStateImplTest.kt
  stream-feeds-android-client/src/test/kotlin/io/getstream/feeds/android/client/internal/state/FeedImplTest.kt
Labels: pr:test

#79 Add `agents.md` to feeds repository
  AGENTS.md
Labels: pr:internal

#80 Compute ownVotes locally and handle answers when updating polls
  stream-feeds-android-client/src/main/kotlin/io/getstream/feeds/android/client/api/model/PollData.kt
  stream-feeds-android-client/src/main/kotlin/io/getstream/feeds/android/client/internal/state/ActivityImpl.kt
  stream-feeds-android-client/src/main/kotlin/io/getstream/feeds/android/client/internal/state/ActivityStateImpl.kt
  stream-feeds-android-client/src/main/kotlin/io/getstream/feeds/android/client/internal/state/FeedStateImpl.kt
  stream-feeds-android-client/src/main/kotlin/io/getstream/feeds/android/client/internal/state/event/handler/ActivityEventHandler.kt
  stream-feeds-android-client/src/main/kotlin/io/getstream/feeds/android/client/internal/state/event/handler/FeedEventHandler.kt
  stream-feeds-android-client/src/main/kotlin/io/getstream/feeds/android/client/internal/utils/List.kt
  stream-feeds-android-client/src/test/kotlin/io/getstream/feeds/android/client/internal/state/ActivityStateImplTest.kt
  stream-feeds-android-client/src/test/kotlin/io/getstream/feeds/android/client/internal/state/FeedStateImplTest.kt
  stream-feeds-android-client/src/test/kotlin/io/getstream/feeds/android/client/internal/state/event/handler/ActivityEventHandlerTest.kt
  stream-feeds-android-client/src/test/kotlin/io/getstream/feeds/android/client/internal/state/event/handler/FeedEventHandlerTest.kt
  stream-feeds-android-client/src/test/kotlin/io/getstream/feeds/android/client/internal/test/TestData.kt
Labels: pr:bug

#84 Keep local `ownReactions` when updating a comment
  stream-feeds-android-client/src/main/kotlin/io/getstream/feeds/android/client/api/model/CommentData.kt
  stream-feeds-android-client/src/main/kotlin/io/getstream/feeds/android/client/api/model/ThreadedCommentData.kt
  stream-feeds-android-client/src/main/kotlin/io/getstream/feeds/android/client/internal/state/ActivityCommentListStateImpl.kt
  stream-feeds-android-client/src/main/kotlin/io/getstream/feeds/android/client/internal/state/CommentListStateImpl.kt
  stream-feeds-android-client/src/main/kotlin/io/getstream/feeds/android/client/internal/state/CommentReplyListStateImpl.kt
  stream-feeds-android-client/src/test/kotlin/io/getstream/feeds/android/client/internal/state/ActivityCommentListStateImplTest.kt
  stream-feeds-android-client/src/test/kotlin/io/getstream/feeds/android/client/internal/state/CommentListStateImplTest.kt
  stream-feeds-android-client/src/test/kotlin/io/getstream/feeds/android/client/internal/state/CommentReplyListStateImplTest.kt
  stream-feeds-android-client/src/test/kotlin/io/getstream/feeds/android/client/internal/test/TestData.kt
Labels: pr:bug
